server:
  port: 9001
spring:
  application:
    name: nacos-provider
  cloud:
    nacos:
      discovery:
        server-addr: 47.100.226.124:8848

#????
management:
  endpoint:
    web:
      exposure:
        include:'*'
