server:
  port: 8401
spring:
  application:
    name: cloud-sentinel-service
  cloud:
    nacos:
      discovery:
        server-addr: 47.100.226.124:8848
    sentinel:
      transport:
        # ??Sentinel dashboard??
        dashboard: localhost:8080
        # ??8719????????????8719+1????????????
        port: 8719
      web-context-unify: false

#????
management:
  endpoint:
    web:
      exposure:
        include:'*'

